[workspace]
members = [
    "remote_core",
    "host",
    "client",
    "protocol",
    "remote_platform",
    "app",
    "remote_client_bridge",
]
resolver = "2"
exclude = ["third_party/ely-gpui-component"]

[patch.crates-io]
gpui-ce = { path = "third_party/gpui-ce" }
blade-graphics = { path = "third_party/blade-graphics" }
screencapturekit = { path = "third_party/screencapturekit" }
